name: Deploy GitHub Pages

on:
    workflow_dispatch: # Trigger only when pushing to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v18.16.0'

      - name: Install dependencies
        run: |
            npm install
            npm run clear
            npm run build
      
      - name: Save build output
        run: |
          mkdir -p ../build-output
          cp -r ./build/* ../build-output/
          
      - name: Verify build-output folder
        run: |
            ls -la ../build-output

      - uses: actions/checkout@v4
        with:
            ref: gh-pages

      - name: Copy build files to gh-pages branch
        run: |
            cp -r ../build-output/* .

      - name: Show changes
        run: ls -la

      - name: Commit
        run: |
          git config --local user.email "kaholau.dev@gmail.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "[Automation] publish gh-pages"
          git push

