name: Deploy GitHub Pages

on:
    workflow_dispatch: # Trigger only when pushing to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v18.16.0'

      - name: Install dependencies
        run: |
            npm install
            npm run clear
            npm run build

      - uses: actions/checkout@v4
        with:
            ref: gh-pages

      - name: Commit
        run: |
          git config --local user.email "kaholau.dev@gmail.com"
          git config --local user.name "github-actions[bot]"
          cp -r ./build/* .
          git add .
          git commit -m "[Automation] publish gh-pages"
          git push

